CREATE OR REPLACE PACKAGE CONTRAINDICATIONS_MEDICAL_HISTORY AS

     PROCEDURE get_words_list (p_id IN PATIENTS.PATIENT_ID%TYPE);
 
     FUNCTION get_words_list_func (p_input_string IN VARCHAR2, his VARCHAR2)RETURN VARCHAR2;
     
     
END CONTRAINDICATIONS_MEDICAL_HISTORY;



 