CREATE TABLE log2 (
  log_id NUMBER PRIMARY KEY,
  MEDICATION_ID NUMBER(38,0),
  NAME VARCHAR2(255),
  DOSAGE_FORM VARCHAR2(255),
  WARNINGS VARCHAR2(255),
  CONTRAINDICATIONS VARCHAR2(255),
  message VARCHAR2(20) NOT NULL,
  log_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);
